### ISSUE TITLE
Tests failing also with nightlies

### ISSUE THREAD

**Issue by BrieucF** [key4hep/k4geo#319] opened 2024-02-14 14:27 UTC
The tests are now failing with the nightlies: https://github.com/key4hep/k4geo/actions/runs/7901882590/job/21566280656?pr=318#step:8:352 . It seems to be linked to the surface plugin. And indeed it looks like tests for detector not using surfaces are passing:

```
2024-02-14T13:44:11.2288800Z 
2024-02-14T13:44:11.2288985Z       Start 15: t_test_ALLEGRO_o1_v02
2024-02-14T13:46:38.8529780Z 15/19 Test #15: t_test_ALLEGRO_o1_v02 ............   Passed  153.07 sec
2024-02-14T13:46:38.8533506Z       Start 16: t_test_ARC_o1_v01_run
2024-02-14T13:47:19.9920566Z 16/19 Test #16: t_test_ARC_o1_v01_run ............   Passed   41.13 sec
2024-02-14T13:47:19.9922024Z       Start 17: t_test_ARC_o1_v01_overlap
2024-02-14T13:50:23.6337826Z 17/19 Test #17: t_test_ARC_o1_v01_overlap ........   Passed  183.64 sec
2024-02-14T13:50:23.6342638Z       Start 18: t_SensThickness_Clic_o2_v4
2024-02-14T13:50:25.6833410Z 18/19 Test #18: t_SensThickness_Clic_o2_v4 .......   Passed    2.05 sec
2024-02-14T13:50:25.6835990Z       Start 19: t_SensThickness_CLIC_o3_v15
2024-02-14T13:50:54.7714564Z 19/19 Test #19: t_SensThickness_CLIC_o3_v15 ......   Passed   29.07 sec
2024-02-14T13:50:54.7738815Z 
2024-02-14T13:50:54.7739458Z 26% tests passed, 14 tests failed out of 19
2024-02-14T13:50:54.7740043Z 
2024-02-14T13:50:54.7806437Z Errors while running CTest
2024-02-14T13:50:54.7809216Z Total Test time (real) = 1466.54 sec
2024-02-14T13:50:54.7809668Z 
2024-02-14T13:50:54.7809864Z The following tests FAILED:
2024-02-14T13:50:54.7810859Z 	  1 - t_test_ILD_l5_v02 (Failed)
2024-02-14T13:50:54.7811642Z 	  2 - t_test_ILD_s5_v02 (Failed)
2024-02-14T13:50:54.7815772Z 	  3 - t_test_ILD_l5_v09 (Failed)
2024-02-14T13:50:54.7816412Z 	  4 - t_test_ILD_l5_v10 (Failed)
2024-02-14T13:50:54.7817321Z 	  5 - t_test_ILD_l5_v11 (Failed)
2024-02-14T13:50:54.7817902Z 	  6 - t_test_SiD_o2_v03 (Failed)
2024-02-14T13:50:54.7818454Z 	  7 - t_test_SiD_o2_v04 (Failed)
2024-02-14T13:50:54.7819015Z 	  8 - t_test_CLIC_o1_v01 (Failed)
2024-02-14T13:50:54.7819575Z 	  9 - t_test_CLIC_o2_v04 (Failed)
2024-02-14T13:50:54.7820177Z 	 10 - t_test_CLIC_o3_v15 (Failed)
2024-02-14T13:50:54.7820747Z 	 11 - t_test_FCCee_o1_v05 (Failed)
2024-02-14T13:50:54.7821775Z 	 12 - t_test_CLD_o2_v05 (Failed)
2024-02-14T13:50:54.7822391Z 	 13 - t_test_steeringFile (Failed)
2024-02-14T13:50:54.7823009Z 	 14 - t_test_IDEA_o1_v02 (Failed)
2024-02-14T13:50:54.7853798Z ##[error]Process completed with exit code 8.
2024-02-14T13:50:54.8169525Z Post job cleanup.
```

**Comment by tmadlener** [comment] 2024-02-14 14:53
The problem seems to be that some extension is missing or has gone missing (from the failing logs):

```
2024-02-14T14:41:48.5236146Z ObjectExtensions::extension ERROR The object has no extension of type 9B1482D0F2AFA965.
```

**Comment by tmadlener** [comment] 2024-02-14 16:12
It also looks like things are running in principle (or at least not crashing). For k4geo it looks like the regex in the CMake config is the thing that makes the test fail.

**Comment by andresailer** [comment] 2024-02-14 16:13
We don't need the surfaces in the simulation (if that is what is missing), but we do need them for the reconstruction.

**Comment by MarkusFrankATcernch** [comment] 2024-02-14 16:37
The surface change cannot be the reason. This is only additional code.
It can only be that the typeid-name somehow changed due to the explicit namespace requirement.

Can one somehow reproduce it? In principle it is enough to beak when this is printed and
check the typeid of the requested object. Then I could create a test doing the same.....

**Comment by andresailer** [comment] 2024-02-15 12:16
Should be fixed with the nightlies for tomorrow.

**Comment by andresailer** [comment] 2024-02-16 09:25
Now the tests are failing because the key4hep action doesn't do install before running ctest
Pinging @jmcarcell

**Comment by jmcarcell** [comment] 2024-02-16 09:28
I added that back, forgot we don't have that working here. Anyway I ran it this morning and there are still some tests failing

**Comment by jmcarcell** [comment] 2024-02-16 09:45
I wanted to mean that the CI installs now and tests are failing: https://github.com/key4hep/k4FWCore/actions/runs/7928420929/job/21646633246?pr=173

**Comment by andresailer** [comment] 2024-02-16 13:28
All tests in k4geo are now OK, except the occasional timeout.

**Closed by andresailer** 2024-02-16 13:28 UTC
